language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-dev npm test

after_success:
  - docker build -t mindaras/multi-nginx ./nginx
  - docker build -t mindaras/multi-client ./client
  - docker build -t mindaras/multi-server ./server
  - docker build -t mindaras/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mindaras/multi-nginx
  - docker push mindaras/multi-client
  - docker push mindaras/multi-server
  - docker push mindaras/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-container
  env: Multicontainer-env
  bucket_name: elasticbeanstalk-eu-central-1-522714423525
  bucket_path: multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY